import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ArrowLeft, ArrowRight, X, Expand } from 'lucide-react';
import { weddingDetails as d } from '../data/weddingDetails';
import { PhotoPlaceholder } from './CoupleSection';
import Reveal from './Reveal';
import { MountainLandscape } from './SceneDecorations';
export default function Gallery() {
  const [active, setActive] = useState(null); const close = useRef(null); const opener = useRef(null);
  const images = d.gallery.filter(photo => photo.src);
  useEffect(() => { if (active === null) return; const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; close.current?.focus(); const onKey = e => { if (e.key === 'Escape') setActive(null); if (e.key === 'ArrowRight') setActive(i => (i + 1) % images.length); if (e.key === 'ArrowLeft') setActive(i => (i + images.length - 1) % images.length); if (e.key === 'Tab') { const buttons = [...document.querySelectorAll('.lightbox button')]; const first = buttons[0], last = buttons.at(-1); if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } } }; document.addEventListener('keydown', onKey); return () => { document.body.style.overflow = previous; document.removeEventListener('keydown', onKey); opener.current?.focus(); }; }, [active, images.length]);
  return <section id="moments" className="gallery-section section-pad"><MountainLandscape/><div className="section-wrap"><Reveal className="gallery-heading"><div><p className="eyebrow">Little moments, endless love</p><h2>Our story, <em>in frames.</em></h2></div><p className="body-copy">Some moments become memories.<br/>Some become forever.</p></Reveal><div className="editorial-gallery">{d.gallery.map((photo, i) => <Reveal className={`gallery-item gallery-${i + 1}`} key={i} delay={(i % 3) * .1}>{photo.src ? <button className="gallery-photo-button" aria-label={`View ${photo.alt}`} onClick={e => { opener.current = e.currentTarget; setActive(images.indexOf(photo)); }}><PhotoPlaceholder src={photo.src} alt={photo.alt} aspectRatio={photo.aspectRatio} kind={i % 2 ? 'mandala' : 'lotus'}/><Expand size={18}/></button> : <PhotoPlaceholder alt={photo.alt} kind={i % 2 ? 'mandala' : 'lotus'}/>}<p><span>{String(i+1).padStart(2,'0')}</span>{photo.caption}</p></Reveal>)}</div></div>{active !== null && createPortal(<div className="lightbox" role="dialog" aria-modal="true" aria-label="Wedding photo gallery" onClick={e => { if (e.target === e.currentTarget) setActive(null); }}><button ref={close} className="lightbox-close" aria-label="Close gallery" onClick={() => setActive(null)}><X/></button><button aria-label="Previous photo" onClick={() => setActive((active + images.length - 1) % images.length)}><ArrowLeft/></button><figure><img src={images[active].src} alt={images[active].alt}/><figcaption>{images[active].caption} · {active + 1} / {images.length}</figcaption></figure><button aria-label="Next photo" onClick={() => setActive((active+1) % images.length)}><ArrowRight/></button></div>, document.body)}</section>;
}
